[apache/helix] -- Enable CI/CD Reporting

diff --git a/.github/workflows/Helix-Manual-CI.yml b/.github/workflows/Helix-Manual-CI.yml
--- a/.github/workflows/Helix-Manual-CI.yml
+++ b/.github/workflows/Helix-Manual-CI.yml
@@ -24,16 +24,23 @@ jobs:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.event.inputs.buildRef }}
-      - name: Set up JDK 1.8
+      - name: Set up JDK 11
         uses: actions/setup-java@v1
         with:
-          java-version: 1.8
-      - name: Delete frontend-maven-plugin dir
-        run: rm -rf .m2\repository\com\github\eirslett
+          java-version: 11
       - name: Build with Maven
         run: mvn clean install -Dmaven.test.skip.exec=true -DretryFailedDeploymentCount=5
       - name: Run All Tests
         run: mvn -B -V -e -ntp "-Dstyle.color=always" ${{ github.event.inputs.mvnOpts }} ${{ github.event.inputs.goals }}
-      - name: Print Tests Results
-        run: .github/scripts/printTestResult.sh
-        if: ${{ success() || failure() }}
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()
+        with:
+          name: Tests Results
+          path: target/surefire-reports/junitreports/TEST-*.xml
+          reporter: java-junit
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: target/surefire-reports/junitreports/TEST-*.xml
